site_name: MicroTBX User Manual
site_description: User Manual for MicroTBX, the Swiss army knife for your firmware.
repo_url: https://github.com/feaser/microtbx
theme: readthedocs
nav:
  - Home: 'index.md'
  - API reference: 'apiref.md'
  - MISRA compliance: 'misra.md'
  - License: 'license.md'
  - Assertions: 'assertions.md'
  - Critical sections: 'critsect.md'
  - Heap: 'heap.md'
  - Memory pools: 'mempools.md'
  - Linked lists: 'lists.md'
  - Random numbers: 'random.md'
  - Checksums: 'checksum.md'
  - Cryptography: 'crypto.md'
  - Platform: 'platform.md'
  - Extra functionality: 'extra.md'
